/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CuDateQuery: typeof import('./src/components/cu-date-query/index.vue')['default']
    CuPicker: typeof import('./src/components/cu-picker/index.vue')['default']
    Loading1: typeof import('./src/components/qiun-loading/loading1.vue')['default']
    Loading2: typeof import('./src/components/qiun-loading/loading2.vue')['default']
    Loading3: typeof import('./src/components/qiun-loading/loading3.vue')['default']
    Loading4: typeof import('./src/components/qiun-loading/loading4.vue')['default']
    Loading5: typeof import('./src/components/qiun-loading/loading5.vue')['default']
    QiunDataCharts: typeof import('./src/components/qiun-data-charts/qiun-data-charts.vue')['default']
    QiunError: typeof import('./src/components/qiun-error/qiun-error.vue')['default']
    QiunLoading: typeof import('./src/components/qiun-loading/qiun-loading.vue')['default']
  }
}
