"""'Change config_value from String to JSON'

Revision ID: d5460b04e5ce
Revises: 
Create Date: 2025-10-08 15:38:49.199390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'd5460b04e5ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_system_dict_data_creator_id', table_name='system_dict_data')
    op.drop_table('system_dict_data')
    op.drop_index('ix_app_job_creator_id', table_name='app_job')
    op.drop_table('app_job')
    op.drop_index('ix_gen_table_column_creator_id', table_name='gen_table_column')
    op.drop_table('gen_table_column')
    op.drop_index('ix_system_position_creator_id', table_name='system_position')
    op.drop_table('system_position')
    op.drop_table('system_role_depts')
    op.drop_table('system_role_menus')
    op.drop_table('system_user_positions')
    op.drop_index('ix_app_myapp_creator_id', table_name='app_myapp')
    op.drop_table('app_myapp')
    op.drop_index('ix_system_dict_type_creator_id', table_name='system_dict_type')
    op.drop_table('system_dict_type')
    op.drop_table('app_job_log')
    op.drop_index('ix_system_role_creator_id', table_name='system_role')
    op.drop_table('system_role')
    op.drop_index('ix_system_users_creator_id', table_name='system_users')
    op.drop_index('ix_system_users_dept_id', table_name='system_users')
    op.drop_table('system_users')
    op.drop_index('ix_system_log_creator_id', table_name='system_log')
    op.drop_table('system_log')
    op.drop_index('ix_system_menu_parent_id', table_name='system_menu')
    op.drop_table('system_menu')
    op.drop_index('ix_system_notice_creator_id', table_name='system_notice')
    op.drop_table('system_notice')
    op.drop_index('ix_system_dept_parent_id', table_name='system_dept')
    op.drop_table('system_dept')
    op.drop_index('ix_app_ai_mcp_creator_id', table_name='app_ai_mcp')
    op.drop_table('app_ai_mcp')
    op.drop_index('ix_system_param_creator_id', table_name='system_param')
    op.drop_table('system_param')
    op.drop_index('ix_gen_demo_creator_id', table_name='gen_demo')
    op.drop_table('gen_demo')
    op.drop_table('system_user_roles')
    op.drop_index('ix_gen_table_creator_id', table_name='gen_table')
    op.drop_table('gen_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gen_table',
    sa.Column('table_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('table_comment', sa.VARCHAR(length=500), nullable=True),
    sa.Column('sub_table_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('sub_table_fk_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('class_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('tpl_category', sa.VARCHAR(length=200), nullable=True),
    sa.Column('tpl_web_type', sa.VARCHAR(length=30), nullable=True),
    sa.Column('package_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('module_name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('business_name', sa.VARCHAR(length=30), nullable=True),
    sa.Column('function_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('function_author', sa.VARCHAR(length=100), nullable=True),
    sa.Column('gen_type', sa.VARCHAR(length=1), nullable=True),
    sa.Column('gen_path', sa.VARCHAR(length=200), nullable=True),
    sa.Column('options', sa.VARCHAR(length=1000), nullable=True),
    sa.Column('creator_id', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['system_users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gen_table_creator_id', 'gen_table', ['creator_id'], unique=False)
    op.create_table('system_user_roles',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('role_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['system_role.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['system_users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('gen_demo',
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=False),
    sa.Column('creator_id', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['system_users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gen_demo_creator_id', 'gen_demo', ['creator_id'], unique=False)
    op.create_table('system_param',
    sa.Column('config_name', sa.VARCHAR(length=500), nullable=False),
    sa.Column('config_key', sa.VARCHAR(length=500), nullable=False),
    sa.Column('config_value', sa.VARCHAR(length=500), nullable=True),
    sa.Column('config_type', sa.BOOLEAN(), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=False),
    sa.Column('creator_id', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['system_users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_key'),
    sa.UniqueConstraint('config_name')
    )
    op.create_index('ix_system_param_creator_id', 'system_param', ['creator_id'], unique=False)
    op.create_table('app_ai_mcp',
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('type', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('command', sa.VARCHAR(length=255), nullable=True),
    sa.Column('args', sa.VARCHAR(length=255), nullable=True),
    sa.Column('env', sqlite.JSON(), nullable=True),
    sa.Column('creator_id', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['system_users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_app_ai_mcp_creator_id', 'app_ai_mcp', ['creator_id'], unique=False)
    op.create_table('system_dept',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), nullable=False),
    sa.Column('order', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=False),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['system_dept.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_system_dept_parent_id', 'system_dept', ['parent_id'], unique=False)
    op.create_table('system_notice',
    sa.Column('notice_title', sa.VARCHAR(length=50), nullable=False),
    sa.Column('notice_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('notice_content', sa.TEXT(), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=False),
    sa.Column('creator_id', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['system_users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_system_notice_creator_id', 'system_notice', ['creator_id'], unique=False)
    op.create_table('system_menu',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('type', sa.INTEGER(), nullable=False),
    sa.Column('order', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.BOOLEAN(), nullable=False),
    sa.Column('permission', sa.VARCHAR(length=100), nullable=True),
    sa.Column('icon', sa.VARCHAR(length=50), nullable=True),
    sa.Column('route_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('route_path', sa.VARCHAR(length=200), nullable=True),
    sa.Column('component_path', sa.VARCHAR(length=200), nullable=True),
    sa.Column('redirect', sa.VARCHAR(length=200), nullable=True),
    sa.Column('hidden', sa.BOOLEAN(), nullable=False),
    sa.Column('keep_alive', sa.BOOLEAN(), nullable=False),
    sa.Column('always_show', sa.BOOLEAN(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=50), nullable=True),
    sa.Column('params', sqlite.JSON(), nullable=True),
    sa.Column('affix', sa.BOOLEAN(), nullable=False),
    sa.Column('parent_id', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['system_menu.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_system_menu_parent_id', 'system_menu', ['parent_id'], unique=False)
    op.create_table('system_log',
    sa.Column('type', sa.INTEGER(), nullable=False),
    sa.Column('request_path', sa.VARCHAR(length=255), nullable=False),
    sa.Column('request_method', sa.VARCHAR(length=10), nullable=False),
    sa.Column('request_payload', sa.TEXT(), nullable=True),
    sa.Column('request_ip', sa.VARCHAR(length=50), nullable=True),
    sa.Column('login_location', sa.VARCHAR(length=255), nullable=True),
    sa.Column('request_os', sa.VARCHAR(length=64), nullable=True),
    sa.Column('request_browser', sa.VARCHAR(length=64), nullable=True),
    sa.Column('response_code', sa.INTEGER(), nullable=False),
    sa.Column('response_json', sa.TEXT(), nullable=True),
    sa.Column('process_time', sa.VARCHAR(length=20), nullable=True),
    sa.Column('creator_id', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['system_users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_system_log_creator_id', 'system_log', ['creator_id'], unique=False)
    op.create_table('system_users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=32), nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), nullable=False),
    sa.Column('name', sa.VARCHAR(length=32), nullable=False),
    sa.Column('status', sa.BOOLEAN(), nullable=False),
    sa.Column('mobile', sa.VARCHAR(length=20), nullable=True),
    sa.Column('email', sa.VARCHAR(length=64), nullable=True),
    sa.Column('gender', sa.VARCHAR(length=1), nullable=True),
    sa.Column('avatar', sa.VARCHAR(length=500), nullable=True),
    sa.Column('is_superuser', sa.BOOLEAN(), nullable=False),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.Column('dept_id', sa.INTEGER(), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('creator_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['system_users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dept_id'], ['system_dept.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('mobile'),
    sa.UniqueConstraint('username')
    )
    op.create_index('ix_system_users_dept_id', 'system_users', ['dept_id'], unique=False)
    op.create_index('ix_system_users_creator_id', 'system_users', ['creator_id'], unique=False)
    op.create_table('system_role',
    sa.Column('name', sa.VARCHAR(length=40), nullable=False),
    sa.Column('code', sa.VARCHAR(length=20), nullable=True),
    sa.Column('order', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.BOOLEAN(), nullable=False),
    sa.Column('data_scope', sa.INTEGER(), nullable=False),
    sa.Column('creator_id', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['system_users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_system_role_creator_id', 'system_role', ['creator_id'], unique=False)
    op.create_table('app_job_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('job_name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('job_group', sa.VARCHAR(length=64), nullable=False),
    sa.Column('job_executor', sa.VARCHAR(length=64), nullable=False),
    sa.Column('invoke_target', sa.VARCHAR(length=500), nullable=False),
    sa.Column('job_args', sa.VARCHAR(length=255), nullable=True),
    sa.Column('job_kwargs', sa.VARCHAR(length=255), nullable=True),
    sa.Column('job_trigger', sa.VARCHAR(length=255), nullable=True),
    sa.Column('job_message', sa.VARCHAR(length=500), nullable=True),
    sa.Column('exception_info', sa.VARCHAR(length=2000), nullable=True),
    sa.Column('job_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=False),
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['app_job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_dict_type',
    sa.Column('dict_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('dict_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('status', sa.BOOLEAN(), nullable=False),
    sa.Column('creator_id', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['system_users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dict_name'),
    sa.UniqueConstraint('dict_type')
    )
    op.create_index('ix_system_dict_type_creator_id', 'system_dict_type', ['creator_id'], unique=False)
    op.create_table('app_myapp',
    sa.Column('name', sa.VARCHAR(length=64), nullable=False),
    sa.Column('status', sa.BOOLEAN(), nullable=False),
    sa.Column('access_url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('icon_url', sa.VARCHAR(length=300), nullable=True),
    sa.Column('creator_id', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['system_users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_app_myapp_creator_id', 'app_myapp', ['creator_id'], unique=False)
    op.create_table('system_user_positions',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('position_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['system_position.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['system_users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'position_id')
    )
    op.create_table('system_role_menus',
    sa.Column('role_id', sa.INTEGER(), nullable=False),
    sa.Column('menu_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['menu_id'], ['system_menu.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['system_role.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'menu_id')
    )
    op.create_table('system_role_depts',
    sa.Column('role_id', sa.INTEGER(), nullable=False),
    sa.Column('dept_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['system_dept.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['system_role.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'dept_id')
    )
    op.create_table('system_position',
    sa.Column('name', sa.VARCHAR(length=40), nullable=False),
    sa.Column('order', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.BOOLEAN(), nullable=False),
    sa.Column('creator_id', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['system_users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_system_position_creator_id', 'system_position', ['creator_id'], unique=False)
    op.create_table('gen_table_column',
    sa.Column('column_name', sa.VARCHAR(length=200), nullable=True),
    sa.Column('column_comment', sa.VARCHAR(length=500), nullable=True),
    sa.Column('column_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('python_type', sa.VARCHAR(length=500), nullable=True),
    sa.Column('python_field', sa.VARCHAR(length=200), nullable=True),
    sa.Column('is_pk', sa.VARCHAR(length=1), nullable=True),
    sa.Column('is_increment', sa.VARCHAR(length=1), nullable=True),
    sa.Column('is_required', sa.VARCHAR(length=1), nullable=True),
    sa.Column('is_unique', sa.VARCHAR(length=1), nullable=True),
    sa.Column('is_insert', sa.VARCHAR(length=1), nullable=True),
    sa.Column('is_edit', sa.VARCHAR(length=1), nullable=True),
    sa.Column('is_list', sa.VARCHAR(length=1), nullable=True),
    sa.Column('is_query', sa.VARCHAR(length=1), nullable=True),
    sa.Column('query_type', sa.VARCHAR(length=200), nullable=True),
    sa.Column('html_type', sa.VARCHAR(length=200), nullable=True),
    sa.Column('dict_type', sa.VARCHAR(length=200), nullable=True),
    sa.Column('sort', sa.INTEGER(), nullable=True),
    sa.Column('table_id', sa.INTEGER(), nullable=True),
    sa.Column('creator_id', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['system_users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['table_id'], ['gen_table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gen_table_column_creator_id', 'gen_table_column', ['creator_id'], unique=False)
    op.create_table('app_job',
    sa.Column('name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('jobstore', sa.VARCHAR(length=64), nullable=True),
    sa.Column('executor', sa.VARCHAR(length=64), nullable=True),
    sa.Column('trigger', sa.VARCHAR(length=64), nullable=False),
    sa.Column('trigger_args', sa.TEXT(), nullable=True),
    sa.Column('func', sa.TEXT(), nullable=False),
    sa.Column('args', sa.TEXT(), nullable=True),
    sa.Column('kwargs', sa.TEXT(), nullable=True),
    sa.Column('coalesce', sa.BOOLEAN(), nullable=True),
    sa.Column('max_instances', sa.INTEGER(), nullable=True),
    sa.Column('start_date', sa.VARCHAR(length=64), nullable=True),
    sa.Column('end_date', sa.VARCHAR(length=64), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=False),
    sa.Column('creator_id', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['system_users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_app_job_creator_id', 'app_job', ['creator_id'], unique=False)
    op.create_table('system_dict_data',
    sa.Column('dict_sort', sa.INTEGER(), nullable=False),
    sa.Column('dict_label', sa.VARCHAR(length=100), nullable=False),
    sa.Column('dict_value', sa.VARCHAR(length=100), nullable=False),
    sa.Column('dict_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('status', sa.BOOLEAN(), nullable=False),
    sa.Column('css_class', sa.VARCHAR(length=100), nullable=True),
    sa.Column('list_class', sa.VARCHAR(length=100), nullable=True),
    sa.Column('is_default', sa.BOOLEAN(), nullable=False),
    sa.Column('dict_type_id', sa.INTEGER(), nullable=True),
    sa.Column('creator_id', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['system_users.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['dict_type_id'], ['system_dict_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_system_dict_data_creator_id', 'system_dict_data', ['creator_id'], unique=False)
    # ### end Alembic commands ###
